// Generated by CoffeeScript 1.8.0
(function() {
  var init, loadCoinSound, playSound, url;

  url = 'http://sota1235.net/coin05.wav';

  init = function(callback) {
    var context, e;
    if (callback == null) {
      callback = function() {};
    }
    try {
      context = new webkitAudioContext();
      return callback(null, context, url);
    } catch (_error) {
      e = _error;
      return callback('Web Audio API is not supported in this browser');
    }
  };

  loadCoinSound = function(context, url, callback) {
    var request;
    if (callback == null) {
      callback = function() {};
    }
    request = new XMLHttpRequest();
    request.open('GET', url, true);
    request.responseType = 'arraybuffer';
    request.send();
    return request.onload = function() {
      return context.decodeAudioData(request.response, function(buffer) {
        return callback(context, buffer);
      });
    };
  };

  playSound = function(context, buffer) {
    var source;
    source = context.createBufferSource();
    source.buffer = buffer;
    source.connect(context.destination);
    return source.start(0);
  };

  window.onload = function() {
    return init(function(err, context, url) {
      if (err) {
        alert(err);
        return;
      }
      return loadCoinSound(context, url, function(context, buf) {
        var btn, coinBuffer;
        coinBuffer = buf;
        btn = document.getElementById('coin');
        return btn.addEventListener('click', function() {
          return playSound(context, coinBuffer);
        });
      });
    });
  };

}).call(this);
