// Generated by CoffeeScript 1.8.0
(function() {
  var context, init;

  context = null;

  init = function() {
    var e;
    try {
      return context = new webkitAudioContext();
    } catch (_error) {
      e = _error;
      return alert('Web Audio API is not supported in this browser');
    }
  };

  window.addEventListener('load', init, false);

}).call(this);
