// Generated by CoffeeScript 1.8.0
(function() {
  var context, dogBarkingBuffer, init, loadDogSound, playSound, url;

  context = null;

  dogBarkingBuffer = null;

  url = 'http://sota1235.net/coin05.wav';

  init = function() {
    var e;
    try {
      context = new webkitAudioContext();
      return loadDogSound(url);
    } catch (_error) {
      e = _error;
      return alert('Web Audio API is not supported in this browser');
    }
  };

  loadDogSound = function(url) {
    var request;
    request = new XMLHttpRequest();
    request.open('GET', url, true);
    request.responseType = 'arraybuffer';
    request.send();
    return request.onload = function() {
      return context.decodeAudioData(request.response, function(buffer) {
        return dogBarkingBuffer = buffer;
      });
    };
  };

  playSound = function(buffer) {
    var source;
    source = context.createBufferSource();
    source.buffer = buffer;
    source.connect(context.destination);
    return source.start(0);
  };

  window.addEventListener('load', init, false);

  setTimeout(function() {
    return playSound(dogBarkingBuffer);
  }, 1000);

}).call(this);
