// Generated by CoffeeScript 1.8.0
(function() {
  var buffer, context, init, loadSound, playSound, url;

  url = 'http://sota1235.net/webAudioAPI/sound/coin.wav';

  buffer = null;

  context = null;

  init = function(callback) {
    var AudioContext, e;
    if (callback == null) {
      callback = function() {};
    }
    try {
      AudioContext = window.AudioContext || window.webkitAudioContext;
      context = new AudioContext();
      return callback(null, context);
    } catch (_error) {
      e = _error;
      return callback('Web Audio API is not supported in this browser');
    }
  };

  loadSound = function(context, url, callback) {
    var request;
    if (callback == null) {
      callback = function() {};
    }
    request = new XMLHttpRequest();
    request.open('GET', url, true);
    request.responseType = 'arraybuffer';
    request.send();
    return request.onload = function() {
      return context.decodeAudioData(request.response, function(buffer) {
        return callback(buffer);
      });
    };
  };

  playSound = function(context, buffer, time) {
    var source;
    source = context.createBufferSource();
    source.buffer = buffer;
    source.connect(context.destination);
    return source.start(time);
  };

  window.onload = init(function(err, con) {
    return context = con;
  });

  loadSound(context, url, function(buf) {
    return buffer = buf;
  });

  $(function() {
    return $('#coin').click(function() {
      return playSound(context, buffer, 0);
    });
  });

}).call(this);
