// Generated by CoffeeScript 1.8.0
(function() {
  var analyser, context, delay, getFreq, init, input;

  init = function(callback) {
    var AudioContext, context, e;
    if (callback == null) {
      callback = function() {};
    }
    try {
      AudioContext = window.AudioContext || window.webkitAudioContext;
      context = new AudioContext();
      return callback(null, context);
    } catch (_error) {
      e = _error;
      return callback('Web Audio API is not suppported in this browser');
    }
  };

  navigator.getUserMedia = navigator.webkitGetUserMedia;

  context = null;

  analyser = null;

  delay = null;

  input = null;

  window.onload = function() {
    return init(function(err, con) {
      var f, fsDivN, i, n50hz, text, _i, _results;
      if (err) {
        alert(err);
        return;
      }
      context = con;
      delay = context.createDelay();
      delay.delayTime.value = 0.07;
      analyser = context.createAnalyser();
      analyser.fftsize = 1024;
      analyser.smoothingTimeContant = 0.9;
      fsDivN = context.sampleRate / analyser.fftsize;
      n50hz = Math.floor(50 / fsDivN);
      _results = [];
      for (i = _i = 0; _i <= 256; i = ++_i) {
        if (i % n50hz === 0) {
          f = Math.floor(50 * (i / n50hz));
          text = f < 1000 ? f + 'Hz' : f / 100 + 'kHz';
          _results.push($('.analyser').append(text + '<div id="' + i.toString() + '"></div>'));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
  };

  $('.start').click(function() {
    if (!navigator.getUserMedia) {
      return alert('WebRTC(getUserMedia) is not suppported...');
    } else {
      console.log('getUserMedia suppported.');
      return navigator.getUserMedia({
        audio: true
      }, function(stream) {
        input = context.createMediaStreamSource(stream);
        input.connect(delay);
        input.connect(analyser);
        return delay.connect(context.destination);
      }, function(err) {
        return console.log('Error: ' + err);
      });
    }
  });

  getFreq = function() {
    var data, i, val, _i, _results;
    data = new Uint8Array(256);
    analyser.getByteFrequencyData(data);
    _results = [];
    for (i = _i = 0; _i <= 256; i = ++_i) {
      val = data[i];
      _results.push($('#' + i.toString()).text(val));
    }
    return _results;
  };

  setInterval(getFreq, 100);

}).call(this);
