// Generated by CoffeeScript 1.8.0
(function() {
  var buffer, context, ext, init, loadSound, playSound, s, sounds, url, _i, _len;

  url = 'http://sota1235.net/webAudioAPI/sound/';

  ext = '.wav';

  sounds = ['#snare', '#hihat', '#bass'];

  buffer = [];

  context = null;

  init = function(callback) {
    var AudioContext, e;
    if (callback == null) {
      callback = function() {};
    }
    try {
      AudioContext = window.AudioContext || window.webkitAudioContext;
      context = new AudioContext();
      return callback(null, context);
    } catch (_error) {
      e = _error;
      return callback('Web Audio API is not supported in this browser');
    }
  };

  loadSound = function(context, url, callback) {
    var request;
    if (callback == null) {
      callback = function() {};
    }
    request = new XMLHttpRequest();
    request.open('GET', url, true);
    request.responseType = 'arraybuffer';
    request.send();
    return request.onload = function() {
      return context.decodeAudioData(request.response, function(buffer) {
        return callback(buffer);
      });
    };
  };

  playSound = function(context, buffer, time) {
    var source;
    source = context.createBufferSource();
    source.buffer = buffer;
    source.connect(context.destination);
    return source.start(time);
  };

  window.onload = init(function(err, con) {
    return context = con;
  });

  for (_i = 0, _len = sounds.length; _i < _len; _i++) {
    s = sounds[_i];
    loadSound(context, url + s.substring(1) + ext, function(buf) {
      return buffer.push(buf);
    });
  }

  $(function() {
    $('#snare').click(function() {
      return playSound(context, buffer[0], 0);
    });
    $('#hihat').click(function() {
      return playSound(context, buffer[1], 0);
    });
    return $('#bass').click(function() {
      return playSound(context, buffer[2], 0);
    });
  });

}).call(this);
